# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RDFDataFormatType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    JSON_LD = "JSON-LD"
    TRIG = "TRIG"
    RDF_XML = "RDF/XML"
    N3 = "N3"
    TURTLE = "TURTLE"
    def __init__(self):  # noqa: E501
        """RDFDataFormatType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'RDFDataFormatType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RDFDataFormatType of this RDFDataFormatType.  # noqa: E501
        :rtype: RDFDataFormatType
        """
        return util.deserialize_model(dikt, cls)
